name: Build and push Docker images for CardioMechanics and its dependencies

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: set image name
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY@L}" >> ${GITHUB_ENV}
        
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to the GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Extract metadata (tags, labels) for main Docker image
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
      
      - name: Build and push VTK Docker image
        id: push-vtk
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          file: ./docker/Dockerfile-thirdparty-vtk
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/thirdparty-vtk
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/thirdparty-vtk:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/thirdparty-vtk:buildcache,mode=max
          push: true
        
      - name: Build and push OpenMPI and PETSc Docker image
        id: push-petsc
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          file: ./docker/Dockerfile-thirdparty-openmpi-petsc
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/thirdparty-openmpi-petsc
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/thirdparty-openmpi-petsc:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/thirdparty-openmpi-petsc:buildcache,mode=max
          push: true

      - name: Build and push main Docker image
        id: push-main
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          file: ./docker/Dockerfile
          build-args: |
            VTK_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/thirdparty-vtk
            OPENMPI_PETSC_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/thirdparty-openmpi-petsc
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
          push: true
